# Generated by Django 6.0.1 on 2026-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
