# Generated by Django 6.0.1 on 2026-01-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_blog_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AUTHOR', 'Author'), ('READER', 'Reader')], default='READER', max_length=10),
        ),
    ]
